# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

before_install:
  - curl -Ls -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build

install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/mate-common
    - autoconf
    - automake
    - gcc
    - git
    - make

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/mate-common
    - autoconf
    - git
    - make
    - xz-utils

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/mate-common.git
    - autoconf
    - automake
    - gcc
    - git
    - make
    - redhat-rpm-config

  ubuntu:
    - autoconf
    - git
    - make
    - xz-utils

variables:
  - CFLAGS="-Wall -Werror=format-security"

after_scripts:
  - make distcheck
